# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.

obj-y  := mx6tabiris.o

ifdef CONFIG_SPL_BUILD
    obj-$(CONFIG_SPL_FRAMEWORK) += mx6tabiris_spl.o
endif
